// client/src/components/Header.tsx
import { useNavigate } from "@tanstack/react-router"

import { useAuth } from "@/context/auth"

import UrlIcon from "./icons/UrlIcon"

export default function Header() {
  const navigate = useNavigate()
  const { user, setUser } = useAuth()

  const handleLogout = async () => {
    try {
      const apiUrl = import.meta.env.VITE_API_URL
      const response = await fetch(`${apiUrl}/api/v1/users/logout`, {
        method: "POST",
        credentials: "include",
        mode: "cors",
        headers: {
          "Content-Type": "application/json",
        },
      })

      if (response.ok) {
        setUser(null)
        navigate({ to: "/login" })
      }
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/70 backdrop-blur-xl">
      <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-sky-400 via-indigo-500 to-fuchsia-500 shadow-lg shadow-indigo-950/30 transition duration-300 hover:-rotate-3 hover:scale-105">
            <UrlIcon size={28} />
          </div>
          <div>
            <p className="text-[0.65rem] font-semibold uppercase tracking-[0.32em] text-sky-200/70">Workspace</p>
            <h1 className="text-xl font-semibold tracking-tight text-white sm:text-2xl">URL Shortener</h1>
          </div>
        </div>
        {user ? (
          <button
            type="button"
            onClick={handleLogout}
            className="inline-flex items-center gap-2 rounded-2xl border border-rose-300/30 bg-rose-400/10 px-4 py-2 text-sm font-semibold text-rose-100 transition hover:-translate-y-0.5 hover:bg-rose-400/15 hover:text-white"
          >
            <svg className="h-[18px] w-[18px]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
              <polyline points="16 17 21 12 16 7" />
              <line x1="21" y1="12" x2="9" y2="12" />
            </svg>
            <span className="hidden sm:inline">Logout</span>
          </button>
        ) : null}
      </div>
    </header>
  )
}

// client/src/components/Header.vue
<template>
  <header>
    <div class="header-container">
      <div class="logo">
        <div class="logo-icon">
          <UrlIcon :size="28" />
        </div>
        <h1>URL Shortener</h1>
      </div>
      <button v-if="userStore.user" @click="handleLogout" class="logout-btn">
        <svg class="logout-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
          <polyline points="16 17 21 12 16 7"></polyline>
          <line x1="21" y1="12" x2="9" y2="12"></line>
        </svg>
        <span>Logout</span>
      </button>
    </div>
  </header>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import UrlIcon from './icons/UrlIcon.vue'
import { userStore } from '@/userStore';

const router = useRouter()

const handleLogout = async () => {
  try {
    const API_URL = import.meta.env.VITE_API_URL
    const res = await fetch(`${API_URL}/api/v1/users/logout`, {
      method: 'POST',
      credentials: 'include',
      mode: 'cors',
      headers: {
        'Content-Type': 'application/json'
      },
    })
    if (res.ok) {
      userStore.user = null
      localStorage.removeItem('user')
      router.push('/login')
    }
  } catch (error) {
    console.log(error)
  }
}
</script>

<style scoped>
header {
  width: 100%;
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 0;
  z-index: 50;
  border-bottom: 1px solid rgba(102, 126, 234, 0.1);
}

.header-container {
  width: 100%;
  padding: 1.25rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  display: flex;
  align-items: center;
  gap: 0.875rem;
}

.logo-icon {
  width: 48px;
  height: 48px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 4px 16px rgba(102, 126, 234, 0.3);
  transition: transform 0.3s ease;
}

.logo-icon:hover {
  transform: rotate(-5deg) scale(1.05);
}

.logo-icon :deep(svg) {
  color: white;
}

h1 {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1a202c;
  letter-spacing: -0.5px;
  margin: 0;
}

.logout-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.625rem 1.25rem;
  background: white;
  color: #e53e3e;
  border: 2px solid #feb2b2;
  border-radius: 10px;
  font-size: 0.9rem;
  font-weight: 600;
  transition: all 0.3s ease;
  box-shadow: 0 2px 8px rgba(229, 62, 62, 0.1);
}

.logout-btn:hover {
  background: #fff5f5;
  border-color: #fc8181;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(229, 62, 62, 0.2);
}

.logout-btn:active {
  transform: translateY(0);
}

.logout-icon {
  width: 18px;
  height: 18px;
}

@media (max-width: 768px) {
  .header-container {
    padding: 1rem 1.5rem;
  }

  .logo-icon {
    width: 42px;
    height: 42px;
  }

  h1 {
    font-size: 1.25rem;
  }

  .logout-btn {
    padding: 0.5rem 1rem;
    font-size: 0.85rem;
  }

  .logout-btn span {
    display: none;
  }

  .logout-icon {
    width: 20px;
    height: 20px;
  }
}
</style>
