// client/src/components/UrlForm.vue
<template>
    <form @submit.prevent="onSubmit">
        <div class="input-wrapper">
            <input type="text" v-model="input" placeholder="Enter your long URL here..." />
            <button type="submit" class="btn btn-primary">
                Shorten URL
                <svg class="arrow-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M5 12h14M12 5l7 7-7 7"/>
                </svg>
            </button>
        </div>
    </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { userStore } from '@/userStore';
import { useToast } from "vue-toastification";

const input = ref('');
const emit = defineEmits(['onSubmit'])

const router = useRouter();
const toast = useToast();

const onSubmit = async () => {
    const API_URL = import.meta.env.VITE_API_URL

    try {
        const res = await fetch(`${API_URL}/api/v1/shorten`, {
            method: 'POST',
            credentials: 'include',
            mode: 'cors',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                url: input.value
            })
        })

        const data = await res.json()

        if (res.ok) {
            toast.success('URL shortened successfully!')
            emit('onSubmit', data)
            input.value = ''
        } else if (res.status === 401) {
            router.push('/login')
            userStore.user = null
            localStorage.removeItem('user')
            toast.error('Session expired, please login again')
        } else {
            console.log(data)
            toast.error('Please enter a valid URL')
        }
    }
    catch (error) {
        console.log(error)
    }
}
</script>

<style scoped>
form {
    width: 100%;
    margin-bottom: 2rem;
    animation: slideUp 0.6s ease-out 0.2s backwards;
}

.input-wrapper {
    position: relative;
    width: 100%;
    background: rgba(255, 255, 255, 0.95);
    border-radius: 16px;
    padding: 0.5rem;
    display: flex;
    gap: 0.5rem;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);
}

input {
    flex: 1;
    padding: 1rem 1.25rem;
    color: #2d3748;
    background: transparent;
    border: none;
    font-size: 1rem;
    font-weight: 500;
}

input::placeholder {
    color: #a0aec0;
}

input:focus {
    outline: none;
}

.btn {
    flex: .5;
    padding: 0.75rem 1.5rem;
    border-radius: 12px;
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    transition: all 0.3s ease;
    white-space: nowrap;
}

.arrow-icon {
    width: 18px;
    height: 18px;
    transition: transform 0.3s ease;
}

.btn:hover:not(:disabled) .arrow-icon {
    transform: translateX(4px);
}

@media (max-width: 768px) {
    .input-wrapper {
        flex-direction: column;
        padding: 0.75rem;
    }

    input {
        padding: 0.75rem 1rem;
        font-size: 0.95rem;
    }

    .btn {
        width: 100%;
    }
}
</style>

// client/src/components/UrlForm.tsx
import { useState } from "react"
import { toast } from "react-toastify"
import { useNavigate } from "@tanstack/react-router"

import { useAuth } from "@/context/auth"
import type { Url } from "@/types"

type UrlFormProps = {
  onSubmit: (url: Url) => void
}

const submitButtonClassName =
  "group inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-sky-400 via-indigo-500 to-fuchsia-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-950/30 transition duration-200 hover:-translate-y-0.5 hover:shadow-xl hover:shadow-indigo-950/40 disabled:translate-y-0 disabled:cursor-not-allowed disabled:opacity-70 md:w-auto"

export default function UrlForm({ onSubmit }: UrlFormProps) {
  const [input, setInput] = useState("")
  const navigate = useNavigate()
  const { setUser } = useAuth()

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const apiUrl = import.meta.env.VITE_API_URL

    try {
      const response = await fetch(`${apiUrl}/api/v1/shorten`, {
        method: "POST",
        credentials: "include",
        mode: "cors",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ url: input }),
      })

      const data = (await response.json()) as Url

      if (response.ok) {
        toast.success("URL shortened successfully!")
        onSubmit(data)
        setInput("")
      } else if (response.status === 401) {
        setUser(null)
        navigate({ to: "/login" })
        toast.error("Session expired, please login again")
      } else {
        console.log(data)
        toast.error("Please enter a valid URL")
      }
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <form className="mb-8 w-full" onSubmit={handleSubmit}>
      <div className="flex w-full flex-col gap-3 rounded-[28px] border border-white/20 bg-white/12 p-3 shadow-2xl shadow-slate-950/25 backdrop-blur-xl md:flex-row">
        <input
          type="text"
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder="Enter your long URL here..."
          className="min-h-12 flex-1 rounded-2xl border border-transparent bg-white/95 px-5 py-4 text-sm font-medium text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-sky-300 focus:ring-4 focus:ring-sky-200/50"
        />
        <button type="submit" className={submitButtonClassName}>
          Shorten URL
          <svg
            className="h-[18px] w-[18px] transition duration-200 group-hover:translate-x-1"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <path d="M5 12h14M12 5l7 7-7 7" />
          </svg>
        </button>
      </div>
    </form>
  )
}
